spring:
  application:
    name: GatedCommunity
  datasource:
    url: jdbc:postgresql://localhost:5436/gatedcommunity
    username: postgres
    password: pos1234
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true


server:
  servlet:
    context-path: /api

#key:
#  access: ${KEY_ACCESS}
#  refresh: ${KEY_REFRESH}

logging:
  file:
    name: logs/log.log
  level:
    root: info


messages:
  hello: hello from Local!
    